language: swift
osx_image: xcode11.2
xcode_project: WhereToGo.xcodeproj
xcode_scheme: WhereToGo
xcode_destination: platform=iOS Simulator,name=iPhone 11

deploy:
  provider: firebase
  token:
    secure: "imJJuDGkKqnIV+R5hIFE19t/KOheQWELsEiaP3+cNcKJqv/+7yIEgHtm91UPn69wp1Vm1HO4joqQU70g3pAimY188FVQl34g33ZYxo6ceSXnWjj2HUnQk1a7YKCGkPL6GJ2Lf8PKyxVNgTGbrJDwpr4UYJWjEMF/0tTj1dzYe1K2/hYksU/JjPIWQXDPwj800xW00ku4eatooPPorC+1yi6LYjAyczqFkC3NGLrFdkv65ZifVILoX19pPwTw4bUg3FYmDYvH5hItIJGXT1fQhToVmTZneNvXR7pxFkljDQyRS2KSEO0tH/ZKLeKsOkZd/4lm0kIfIEnEo+hbkmWKTzushwPC0KO+HfaCyB0tWHBkfIqSVeY8HXnqo5PJ+mpGUF7o2IvBAW56/DpkaGSqab0u23uP0VvkyIpjKOIyHTHxjNDn2nwOgPu6JsX8wSLvVkOBtQSuWjSxsZvkv5GkybvOkOp18bu2sKnrplrhVKFINq8XV72DdirVeL7JHYa3bdTwDf/NkShczJguazrS0a6grwXIJ6UbxhTJPKtFTZsRUjWpuLCoAe4BDz6GKWCn9oziCJORLhkTJieLtpZ5937IeEpfbijENiD+WnabQ3a8mRAOqrDVkGrAH15XJC26KIhVufV0LPTRCOk+ZAqiONxWeadW7KDIFBm9WeXdFUk="

project: "WhereToGo"